import { access, mkdir, mkdtemp, readFile, readdir, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import ts from 'typescript'
import { afterEach, describe, expect, it } from 'vitest'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const temporaryDirectories: string[] = []

afterEach(async () => {
  await Promise.all(temporaryDirectories.splice(0).map(path => rm(path, { recursive: true, force: true })))
})

describe('built public declaration artifacts', () => {
  it('publishes generator-owned Host Typert and Client remote artifacts', async () => {
    const generated = {
      hostJavaScript: await readFile(join(root, 'lib/typert.host.js'), 'utf8'),
      hostJavaScriptMap: await readFile(join(root, 'lib/typert.host.js.map'), 'utf8'),
      hostDeclaration: await readFile(join(root, 'lib/typert.host.d.ts'), 'utf8'),
      remoteJavaScript: await readFile(join(root, 'lib/typert.remote-client.js'), 'utf8'),
      remoteJavaScriptMap: await readFile(join(root, 'lib/typert.remote-client.js.map'), 'utf8'),
      remoteDeclaration: await readFile(join(root, 'lib/typert.remote-client.d.ts'), 'utf8'),
      remoteDeclarationMap: await readFile(join(root, 'lib/typert.remote-client.d.ts.map'), 'utf8'),
    }

    expect(generated.hostJavaScript.split('\n')[0]).toBe(generated.hostDeclaration.split('\n')[0])
    expect(generated.remoteJavaScript.split('\n')[0]).toBe(generated.remoteDeclaration.split('\n')[0])
    expect(generated.hostJavaScript.split('\n')[0]).toContain('Generated by @deepseek-ai/dsh-typert-generator')
    expect(generated.remoteJavaScript.split('\n')[0]).toContain('Generated by @deepseek-ai/dsh-typert-generator')
    expect(generated.hostJavaScript).not.toMatch(/\b(?:import|export)\s+(?:[^'";]*?\s+from\s+)?['"][^'"]+['"]/u)
    expect(generated.remoteJavaScript).not.toMatch(/\b(?:import|export)\s+(?:[^'";]*?\s+from\s+)?['"][^'"]+['"]/u)
    expect(generated.hostJavaScript).not.toContain("from 'zod'")
    expect(generated.remoteJavaScript).not.toContain("from 'zod'")
    expect(generated.hostJavaScript).toContain('export {')
    expect(generated.hostJavaScript).toContain('TYPERT')
    expect(generated.remoteJavaScript).toContain('export {')
    expect(generated.remoteJavaScript).toContain('TYPERT_REMOTE as default')
    expect(generated.remoteJavaScript).toMatch(/namespace:\s*["']pluginStatus["']/u)
    expect(generated.remoteJavaScript).toMatch(/method:\s*["']get["']/u)
    for (const sourceMap of [
      generated.hostJavaScriptMap,
      generated.remoteJavaScriptMap,
    ]) {
      const parsed = JSON.parse(sourceMap) as { sourcesContent?: unknown[] }
      expect(parsed.sourcesContent?.length).toBeGreaterThan(0)
      expect(parsed.sourcesContent?.every(content => typeof content === 'string')).toBe(true)
    }
    expect((JSON.parse(generated.remoteDeclarationMap) as { sources?: unknown[] }).sources?.length).toBeGreaterThan(0)
    const clientJavaScript = await readFile(join(root, 'lib/client.js'), 'utf8')
    expect(clientJavaScript).toContain('harness-comfyui#pluginStatus/get')
    expect(clientJavaScript).toContain('$mount')
    expect(clientJavaScript).not.toContain('require("zod")')
    expect((await readdir(join(root, 'lib/types'))).filter(name => name.endsWith('.d.ts')).sort()).toEqual([
      'client.d.ts',
      'index.d.ts',
      'types.d.ts',
    ])
  })

  it('resolves Host and Client exports from a TypeScript consumer', async () => {
    const hostTypes = join(root, 'lib/types/index.d.ts')
    const clientTypes = join(root, 'lib/types/client.d.ts')
    await expect(access(hostTypes)).resolves.toBeUndefined()
    await expect(access(clientTypes)).resolves.toBeUndefined()
    await expect(readFile(hostTypes, 'utf8')).resolves.toContain('export {')
    await expect(readFile(clientTypes, 'utf8')).resolves.toContain('export {')

    const directory = await mkdtemp(join(tmpdir(), 'harness-comfyui-artifact-consumer-'))
    temporaryDirectories.push(directory)
    await mkdir(join(directory, 'node_modules'), { recursive: true })
    await symlink(root, join(directory, 'node_modules', 'harness-comfyui'), 'dir')
    const consumer = join(directory, 'consumer.ts')
    await writeFile(consumer, [
      "import { apply as applyHost, type Config, type PluginStatus } from 'harness-comfyui'",
      "import { apply as applyClient } from 'harness-comfyui/client'",
      "import type { PluginStatus as PublicPluginStatus } from 'harness-comfyui/types'",
      "const host: typeof applyHost = applyHost",
      "const client: typeof applyClient = applyClient",
      "const config: Config = { configurationProfile: 'test' }",
      "const status: PluginStatus = { packageName: 'harness-comfyui', packageVersion: '0.1.0-rc.7', configurationProfile: 'test', hostLoaded: true }",
      'const publicStatus: PublicPluginStatus = status',
      'void host; void client; void config; void status; void publicStatus',
      '',
    ].join('\n'), 'utf8')

    const program = ts.createProgram([consumer], {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      strict: true,
      noEmit: true,
      skipLibCheck: false,
      types: ['node'],
    })
    const diagnostics = ts.getPreEmitDiagnostics(program)
    expect(diagnostics.map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'))).toEqual([])
  }, 30_000)
})
