import { createRequire } from 'node:module'
import { mkdtemp, readFile, realpath, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'

import { Context } from '@deepseek-ai/cordis'
import { typertPlugin } from '@deepseek-ai/dsh-typert-generator/tsdown'
import { build } from 'tsdown'
import { afterEach, describe, expect, it } from 'vitest'
import { createElement, type ReactNode } from 'react'
import type { ILayout } from '@deepseek-ai/dsh-client-ui-layout/client'
import type { SlotRegistry as SlotRegistryType } from '@deepseek-ai/dsh-client-runtime/client'

import { buildClientBundle } from '../../scripts/build/tsdown-client-bundle.ts'
import { bundleGeneratedTypert } from '../../scripts/build/bundle-generated-typert.ts'
import { standaloneTypertWorkspacePlugin } from '../../scripts/build/standalone-typert-plugin.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const temporaryDirectories: string[] = []
const { renderToStaticMarkup } = createRequire(import.meta.url)('react-dom/server') as {
  renderToStaticMarkup(node: ReactNode): string
}
type RuntimeClientExports = {
  SlotRegistry: typeof SlotRegistryType
  defineStore: typeof import('@deepseek-ai/dsh-client-runtime/client').defineStore
}
type ClientPlugin = {
  name: string
  inject: string[]
  apply(ctx: Context): void
}

async function generateIsolatedTypertWorkspace(directory: string): Promise<string> {
  const workspaceRoot = join(directory, 'typert-workspace')
  const packageRoot = join(workspaceRoot, 'packages', 'harness-comfyui')
  const bundles = await build({
    config: false,
    entry: { index: join(packageRoot, 'src/index.ts') },
    outDir: join(packageRoot, 'lib'),
    format: 'esm',
    platform: 'node',
    target: 'node22.19.0',
    fixedExtension: false,
    dts: false,
    clean: false,
    plugins: [
      typertPlugin({ mode: 'package', faces: ['host'] }),
      standaloneTypertWorkspacePlugin({
        workspaceRoot,
        outputDirectory: join(directory, 'generated-typert'),
        cleanupWorkspace: false,
      }),
    ],
  })
  try {
    await bundleGeneratedTypert({ directory: join(packageRoot, 'lib') })
    return packageRoot
  } finally {
    await Promise.all(bundles.map(bundle => bundle[Symbol.asyncDispose]()))
  }
}

async function loadSlotRegistry() {
  const require = createRequire(import.meta.url)
  const clientModules = new Map<string, RuntimeClientExports>()
  const hadWindow = Object.hasOwn(globalThis, 'window')
  const previousWindow = globalThis.window
  Object.defineProperty(globalThis, 'window', {
    configurable: true,
    value: {
    __ModuleLoader__: {
      load({ id, factory }: { id: string; factory: (require: (specifier: string) => unknown) => RuntimeClientExports }) {
        clientModules.set(id, factory(require))
      },
    },
    },
  })
  try {
    await import('@deepseek-ai/dsh-client-runtime/client')
    const runtimeExports = clientModules.get('@deepseek-ai/dsh-client-runtime')
    if (!runtimeExports) throw new Error('runtime client did not register with ModuleLoader')
    return runtimeExports
  } finally {
    if (hadWindow) {
      Object.defineProperty(globalThis, 'window', { configurable: true, value: previousWindow })
    } else {
      Reflect.deleteProperty(globalThis, 'window')
    }
  }
}

describe('built Client bundle boundary', () => {
  afterEach(async () => {
    await Promise.all(temporaryDirectories.splice(0).map(path => rm(path, { recursive: true, force: true })))
  })

  it('loads through ModuleLoader, mounts the generated Remote, and composes the project root', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'harness-comfyui-built-client-'))
    temporaryDirectories.push(directory)
    const packageRoot = await generateIsolatedTypertWorkspace(directory)
    const generatedRemote = join(packageRoot, 'lib', 'typert.remote-client.js')
    expect(await readFile(generatedRemote, 'utf8')).toMatch(
      /^\/\* Generated by @deepseek-ai\/dsh-typert-generator\b.*\*\//u,
    )
    const output = join(directory, 'lib', 'client.js')
    await buildClientBundle({
      entry: join(packageRoot, 'src/client/index.tsx'),
      css: join(packageRoot, 'src/client/styles.css'),
      output,
    })

    const clientSourceMap = JSON.parse(await readFile(`${output}.map`, 'utf8')) as {
      sourceRoot?: string
      sources: string[]
      sourcesContent: Array<string | null>
    }
    const resolvedSources = await Promise.all(clientSourceMap.sources.map(async source => {
      const sourcePath = resolve(dirname(output), clientSourceMap.sourceRoot ?? '', source)
      return realpath(sourcePath).catch(() => sourcePath)
    }))
    const generatedRemotePath = await realpath(generatedRemote)
    const generatedRemoteIndex = resolvedSources.indexOf(generatedRemotePath)
    expect(generatedRemoteIndex).toBeGreaterThanOrEqual(0)
    expect(clientSourceMap.sourcesContent[generatedRemoteIndex]).toMatch(
      /^\/\* Generated by @deepseek-ai\/dsh-typert-generator\b.*pluginStatus/su,
    )
    expect(resolvedSources).not.toContain(join(root, 'lib', 'typert.remote-client.js'))

    const createDomElement = () => {
      const values = new Map<string, string>()
      const attributes = new Map<string, string>()
      return {
        style: {
          getPropertyPriority: () => '',
          getPropertyValue: (name: string) => values.get(name) ?? '',
          removeProperty: (name: string) => values.delete(name),
          setProperty: (name: string, value: string) => {
            values.set(name, value)
          },
        },
        getAttribute: (name: string) => attributes.get(name) ?? null,
        hasAttribute: (name: string) => attributes.has(name),
        removeAttribute: (name: string) => attributes.delete(name),
        setAttribute: (name: string, value: string) => {
          attributes.set(name, value)
        },
      }
    }
    const styleElements: Array<{ dataset: Record<string, string>; textContent: string }> = []
    const document = {
      documentElement: createDomElement(),
      body: createDomElement(),
      head: {
        appendChild(element: (typeof styleElements)[number]) {
          styleElements.push(element)
        },
      },
      createElement() {
        return { dataset: {}, textContent: '' }
      },
      querySelector(selector: string) {
        return selector === 'style[data-plugin="harness-comfyui"]' ? styleElements[0] : undefined
      },
    }
    let handoff: { id: string; factory: (require: (specifier: string) => unknown) => ClientPlugin } | undefined
    const window = {
      __ModuleLoader__: {
        load(value: typeof handoff) {
          handoff = value
        },
      },
    }
    vm.runInNewContext(await readFile(output, 'utf8'), { document, window })

    expect(handoff?.id).toBe('harness-comfyui')
    expect(handoff?.factory).toBeTypeOf('function')
    const runtimeExports = await loadSlotRegistry()
    const requireExternal = (specifier: string): unknown => {
      if (specifier === '@deepseek-ai/dsh-client-runtime/client') return runtimeExports
      if (specifier === 'react' || specifier === 'react/jsx-runtime') {
        return createRequire(import.meta.url)(specifier)
      }
      throw new Error(`built bundle unexpectedly required ${specifier}`)
    }
    if (!handoff) throw new Error('Client bundle did not register with ModuleLoader')
    const plugin = handoff.factory(requireExternal)
    handoff.factory(requireExternal)
    expect(styleElements).toHaveLength(1)
    expect(styleElements[0]?.dataset.plugin).toBe('harness-comfyui')
    expect(styleElements[0]?.textContent).toBe(await readFile(join(packageRoot, 'src/client/styles.css'), 'utf8'))
    expect(plugin).toMatchObject({
      name: 'harness-comfyui',
      inject: ['slots', 'sessions', 'remote', 'theme', 'inputTriggers'],
    })
    expect(plugin?.apply).toBeTypeOf('function')

    const SlotRegistry = runtimeExports.SlotRegistry
    const ctx = new Context()
    await ctx.plugin(SlotRegistry)
    const mountedContributions: unknown[] = []
    let remoteUnmountCount = 0
    const remoteDisposer = ctx.provide('remote', {
      $mount: async (contribution: unknown) => {
        mountedContributions.push(contribution)
        return async () => {
          remoteUnmountCount += 1
        }
      },
    })
    const sessionsDisposer = ctx.provide('sessions', {})
    const themeDisposer = ctx.provide('theme', {
      getTheme: () => ({ active: { colorScheme: 'light' as const, tokens: {} } }),
    })
    const inputTriggersDisposer = ctx.provide('inputTriggers', {})
    const clientFiber = ctx.plugin(plugin)
    await clientFiber

    expect(mountedContributions).toHaveLength(1)
    expect(mountedContributions[0]).toMatchObject({ package: 'harness-comfyui' })
    expect((mountedContributions[0] as { descriptors: Array<{ service: string; method: string }> }).descriptors)
      .toContainEqual(expect.objectContaining({ service: 'pluginStatus', method: 'get' }))
    expect(ctx.slots.entries('root')).toHaveLength(1)
    expect(ctx.slots.entries('sidebar')).toHaveLength(0)
    expect(ctx.slots.entries('conversation')).toHaveLength(0)
    expect(ctx.slots.entries('details')).toHaveLength(0)
    expect(ctx.slots.entries('shell.overlay')).toHaveLength(0)

    const rootSnapshot = ctx.slots.snapshot('root')
    expect(rootSnapshot).toHaveLength(1)
    expect(rootSnapshot[0]?.children.map(child => child.name)).toEqual([
      'sidebar',
      'conversation',
      'details',
      'shell.overlay',
    ])

    const layout = ctx.reflect.get('layout') as ILayout | undefined
    expect(layout).toBeDefined()
    if (!layout) throw new Error('project layout service was not provided')

    const rootEntry = ctx.slots.entriesOfSlot('root')[0]
    const rootComponent = rootEntry?.component as ((props: {
      renderSlot: (key: string, owner: object) => ReactNode
    }) => ReactNode) | undefined
    expect(rootComponent).toBeTypeOf('function')
    if (!rootComponent) throw new Error('project root component was not registered')

    const renderCalls: Array<{ key: string; owner: object }> = []
    const renderRoot = () => {
      renderCalls.length = 0
      return renderToStaticMarkup(createElement(rootComponent, {
        renderSlot(key, owner) {
          renderCalls.push({ key, owner })
          return createElement('span', { 'data-rendered-slot': key })
        },
      }))
    }

    const initialMarkup = renderRoot()
    expect(initialMarkup).toContain('294px minmax(0, 1fr) 432px')
    expect(renderCalls).toEqual([
      { key: 'sidebar', owner: { collapsed: false, width: 294 } },
      { key: 'conversation', owner: {} },
      { key: 'details', owner: {} },
      { key: 'shell.overlay', owner: {} },
    ])
    expect(initialMarkup.indexOf('data-layout-column="details"')).toBeLessThan(
      initialMarkup.indexOf('data-shell-overlay'),
    )

    layout.toggleSidebar()
    const collapsedMarkup = renderRoot()
    expect(collapsedMarkup).toContain('56px minmax(0, 1fr) 432px')
    expect(renderCalls[0]).toEqual({ key: 'sidebar', owner: { collapsed: true, width: 56 } })

    layout.toggleSidebar()
    expect(renderRoot()).toContain('294px minmax(0, 1fr) 432px')
    layout.closeDetails()
    expect(renderRoot()).toContain('294px minmax(0, 1fr) 0px')
    layout.openDetails()
    expect(renderRoot()).toContain('294px minmax(0, 1fr) 432px')

    await clientFiber.dispose()
    expect(ctx.slots.entries('root')).toHaveLength(0)
    expect(ctx.slots.snapshot('root')[0]?.children).toEqual([])
    expect(ctx.reflect.get('layout')).toBeUndefined()
    expect(document.documentElement.style.getPropertyValue('color-scheme')).toBe('')
    expect(document.body.hasAttribute('data-ds-dark-theme')).toBe(false)
    expect(remoteUnmountCount).toBe(1)
    inputTriggersDisposer()
    themeDisposer()
    sessionsDisposer()
    await remoteDisposer()
    await ctx.fiber.dispose()
  })
})
