import { describe, expect, it } from 'vitest'

import { validateGeneratedTypertOutput } from '../../scripts/build/bundle-generated-typert.ts'

const marker = '/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */'

function validOutputs(code = `${marker}\nconst TYPERT = { face: 'host' }\nexport { TYPERT }\n`) {
  return [
    {
      type: 'chunk' as const,
      fileName: 'typert.host.js',
      code,
      exports: ['TYPERT'],
      isEntry: true,
    },
    {
      type: 'asset' as const,
      fileName: 'typert.host.js.map',
      source: JSON.stringify({ sources: ['typert.host.js'], sourcesContent: [code] }),
    },
  ]
}

const expectation = {
  fileName: 'typert.host.js',
  exports: ['TYPERT'],
  requiredSnippets: ["face: 'host'"],
}

describe('generated Typert post-build validation', () => {
  it('returns the unique JavaScript and source-map outputs with the raw official marker', () => {
    expect(validateGeneratedTypertOutput(`${marker}\nimport { z } from 'zod'\n`, validOutputs(), expectation)).toEqual({
      code: validOutputs()[0]!.code,
      map: validOutputs()[1]!.source,
      marker,
    })
  })

  it('rejects an extra generated chunk', () => {
    const outputs = [
      ...validOutputs(),
      { type: 'chunk' as const, fileName: 'shared.js', code: 'export {}\n', exports: [], isEntry: false },
    ]
    expect(() => validateGeneratedTypertOutput(`${marker}\n`, outputs, expectation)).toThrow(/exactly one JavaScript chunk and one source map/i)
  })

  it('rejects an unresolved external import', () => {
    const outputs = validOutputs(`${marker}\nimport { z } from 'zod'\nconst TYPERT = { face: 'host' }\nexport { TYPERT }\n`)
    expect(() => validateGeneratedTypertOutput(`${marker}\n`, outputs, expectation)).toThrow(/external import.*zod/i)
  })

  it('rejects raw generator output without its official first-line marker', () => {
    expect(() => validateGeneratedTypertOutput("import { z } from 'zod'\n", validOutputs(), expectation)).toThrow(/official first-line marker/i)
  })
})
